### ISSUE TITLE
Broken entries

### ISSUE THREAD

**Issue by avivace** [gbdev/database#116]
- https://hh.gbdev.io/game/rez (rom not working)
- https://hh.gbdev.io/game/gejmbay-j (rom not working)

**Comment by dag7dev** [comment]
- rez: it is working (press start and arrows, it works)
- the entry you was referring to doesn't exist anymore (I think it was duped). The correct link is: https://hh.gbdev.io/game/gejmbaj and it works.

We can safely close this.

**Comment by avivace** [comment]
> * rez: it is working (press start and arrows, it works)
> 
>     * the entry you was referring to doesn't exist anymore (I think it was duped). The correct link is: https://hh.gbdev.io/game/gejmbaj and it works.
> 
> 
> We can safely close this.

Good catch, thanks!
