### ISSUE TITLE
NSFW Tag

### ISSUE THREAD

**Issue by dag7dev** [gbdev/database#123]
Add 'nsfw' tag.
In the main frontend, we won't show by default homebrew having this tag.
(also, it is useful for people who wants to see just 'nsfw' homebrew)

**Comment by avivace** [comment]
The NSFW tag was added in the schema more than 3 years ago.. https://github.com/gbdev/database/commit/ff0a1a22b6685488712d60bce1ed6480294ab6d2

What needs to be done is actually:

- Review (every?) game and start to apply the NSFW tag where needed
- Allow the backend to filter for the flag (do we have simple filter routes?)

Maybe we can open issues for this related stuff?

**Comment by dag7dev** [comment]
@avivace I opened this issue because I was giving a quick peek in the schema and nsfw wasn't available in tags.
I've double checked now and it is a boolean.

Should we transform it in a tag so the json would be less verbose?
