### ISSUE TITLE
Add link field for cartridge selling

### ISSUE THREAD

**Issue by avivace** [gbdev/database#140]
If the game is sold on cartridge somewhere, a specific link could allow rending a "Buy cartridge and support author" button. E.g. see #139 

To be included in Draft 4: https://github.com/gbdev/database/pull/126

**Comment by dag7dev** [comment]
Wouldn't it be nicer to just leave the link to homepage of the game / project?

I mean, author will take care of updating its homepage with all the links he retain to be more suitable for its needs, I don´t think we really need a specific field to manage buying the cartridge... (note that we already have a "website" field).

We should leave to the author the freedom of managing its own stuff, we shall act like a showcase.
