### ISSUE TITLE
are gif screenshots allowed?

### ISSUE THREAD

**Issue by zlago** [gbdev/database#192]
according to [contributing.md](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/CONTRIBUTING.md#2-create-the-game-folder-and-add-the-related-files), screenshots only support `.png`, `.jpg` and `.bmp`, but [dango dash](https://github.com/gbdev/database/tree/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash) [uses a `.gif`](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash/%2BoCTM7.gif) [as the first screenshot](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash/game.json#L13)

**Comment by avivace** [comment]
> according to [contributing.md](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/CONTRIBUTING.md#2-create-the-game-folder-and-add-the-related-files), screenshots only support `.png`, `.jpg` and `.bmp`, but [dango dash](https://github.com/gbdev/database/tree/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash) [uses a `.gif`](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash/%2BoCTM7.gif) [as the first screenshot](https://github.com/gbdev/database/blob/4f3a9a0e7e006cce312a4add90792794d4ff6408/entries/dango-dash/game.json#L13)

Woops, you are right. Some gifs were inadvertently added when using automatic scrapers. If you want, go ahead and add GIFs (or webm) in the screenshots. I would however avoid considering the use of GIFs in screenshots as a given 'feature'. At some point animated and non-animated media will be split, so don't expect Homebrew Hub to continue displaying animated assets as "previews" e.g. in standard search results.
