### ISSUE TITLE
Broken entries

### ISSUE THREAD

**Issue by avivace** [gbdev/database#197]
- rinkapink

**Comment by dag7dev** [comment]
https://hh.gbdev.io/game/fatass
This also doesn't load, it says "invalid rom" but I tried on another emulator and it works.

**Comment by dag7dev** [comment]
(see #116 for rinkapink)

**Comment by avivace** [comment]
> (see #116 for rinkapink)
> 
> https://hh.gbdev.io/game/fatass This also doesn't load, it says "invalid rom" but I tried on another emulator and it works.

Okay, we can disable the online play then

**Comment by avivace** [comment]
Fixed in https://github.com/gbdev/database/commit/47abfcd74058c9395af25c761e1395652c781f95
