### ISSUE TITLE
Multiple ROMs

### ISSUE THREAD

**Issue by avivace** [gbdev/database#20]
How should we support more ROM files?
An array of ROM objects, where a single ROM entry is described by:

- `name`
- `path`
- `version` ?
- `description`
- [`sha1`,`sha256`, `md5`] hashes

Also, allow the emulator to change to ROM to play

**Comment by tobiasvl** [comment]
What games is this applicable to?

**Comment by avivace** [comment]
- [`sha1`,`sha256`, `md5`] hashes - everything
- `name` - in case of multiple roms for game
- `path` - this is just a post-computable value, since the path is deterministic given romname+gameslug
- `version` - in case of multiple roms for game
- `description` - in case of multiple roms for game, why are there more files and in which they differ

Multiple roms for game can happen in this scenarios:

- In active development game (should we care? just have the last build and link to the repository for more details)
- Old entries with a lot of builds circulating
- Demo's entry including more parts

**Comment by avivace** [comment]
Also, how to flag the *default* ROM? (The one automatically played when opening the page?)

**Comment by avivace** [comment]
Handled in https://github.com/gbdev/database/commit/fb2072a7a7f34f23888a01a39e34ff455552db32#diff-b20fa8d890cc22042bc311475dfff212
