### ISSUE TITLE
Make slug lowecase

### ISSUE THREAD

**Issue by avivace** [gbdev/database#208]
Atm there may exists two different entries with different casing `test` and `Test` will resolve to different entries. We should make every slug (folder names + slug property in the metadata) lowercase and ensure that the schema enforces it (along with having the dash as the only other permitted character in the string so we can stay URL safe)

**Comment by dag7dev** [comment]
I think this is related to https://github.com/gbdev/database/issues/161 , and will lead to conflicts.

How we exactly would like to proceed?

Examples:
- a big MR that makes everything lowercase and renames folders if they have the same slug appending a suffix
- a MR with a commit for each every camelcase entry that will be merged into a lowered case one
- ...

**Comment by avivace** [comment]
@dag7dev you're right, we need to fix #161 first..
