### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by avivace** [gbdev/database#22]
- [Game Boy Demospotting](http://privat.bahnhof.se/wb800787/gb/)
- [Pdroms](http://pdroms.de/)
- [pdroms files directory](http://pdroms.de/files/gameboy/)
- [demozoo](https://demozoo.org/platforms/38/)

**Comment by tobiasvl** [comment]
Could be useful to scroll through the archive of http://gbdk-developers.com/ as well (but probably not possible to script it).

**Comment by avivace** [comment]
Tumblr, maybe there's already some scraping library/script to do it

**Comment by tobiasvl** [comment]
http://www.romhacking.net/homebrew/

**Comment by avivace** [comment]
[gbdev2014-allroms.zip](https://github.com/dmg01/database/files/1716525/gbdev2014-allroms.zip)

**Comment by avivace** [comment]
http://www.nesworld.com/article.php?system=gbc&data=gbchomebrew

https://github.com/avivace/awesome-gbdev#games

https://github.com/avivace/awesome-gbdev#games

Should we have a 'source' issue tag and track the progress on dumping each source separately?

**Comment by tobiasvl** [comment]
That would probably be a good idea.

**Comment by avivace** [comment]
Ok, we'll split

**Comment by avivace** [comment]
Split in #25 #26 #27 #28 #29 #30 #31 #32 .

**Comment by dag7dev** [comment]
I'd suggest this one too: http://privat.bahnhof.se/wb800787/gb/demos/ (it is the old http://gameboy.modermodemet.se/)

**Comment by avivace** [comment]
> ~I'd suggest this one too: http://privat.bahnhof.se/wb800787/gb/demos/ (it is the old http://gameboy.modermodemet.se/)~
> 
> Issue hasn't been created, that's why I wrote it here.

?

**Comment by dag7dev** [comment]
Yesterday I discovered modermodemet as source, then I found that you already put the updated link (banhof).

While re-reading this thread for a while, I don't think a source issue related to "banhof" has been already created /merged.

Or is it?

**Comment by avivace** [comment]
> Yesterday I discovered modermodemet as source, then I found that you already put the updated link (banhof). While re-reading this thread for a while, I don't think a source issue related to "banhof" has been already created /merged. Or is it?

Demospotting, previously hosted at http://gameboy.modermodemet.se/ and now http://privat.bahnhof.se/wb800787/gb/demos/ has been scraped by https://github.com/gbdev/database/blob/48dab96315b899a3a822792290d73a646ac9f2f0/scrapers/demospotting/README.md
Does this clarify your doubt?
