### ISSUE TITLE
RFC: Represent commercial releases

### ISSUE THREAD

**Issue by avivace** [gbdev/database#230]
How would we want to represent the commercial availability of an homebrew in the db? Should we have fields to "buy" the ROM/order physical cartridges?

**Comment by dag7dev** [comment]
I think the link to itch.io page/whatever to support the original author is sufficient.

**Comment by dag7dev** [comment]
maybe a new "store" field could be an idea

**Comment by avivace** [comment]
> I think the link to itch.io page/whatever to support the original author is sufficient.

We have this already as "website", but there are free/libre homebrews which have an itch.io page as well so there's no way atm to discern commercial releases based on that.

I would suggest to have a boolean field "commercial" ? Then maybe an additional link field where we can add kickstarter, shop where to buy the physical version, shop where to buy the digital (which may overlap with itch.io, for example)..

**Comment by dag7dev** [comment]
@avivace maybe something like this?
```
commercial: yes
commercial_links: {
    url: "https itch io",
    description: "store's link"
}
```
?

**Comment by avivace** [comment]
@dag7dev agree on the boolean, but we already have a website array, maybe we can just add those links there?

https://github.com/gbdev/database/blob/master/game-schema-d4.json#L130

or we can add an enum with the "link type" which can be like "shop" "cartridge-shop"?

**Comment by dag7dev** [comment]
I think just a "shop" link is enough

**Comment by asiekierka** [comment]
I'd agree, but we also need to - IMO - distinguish between entries which have a way to buy *the same ROM*, and entries which have a way to buy *an enhanced ROM* (say, a full version of a game's demo).

**Comment by avivace** [comment]
> I'd agree, but we also need to - IMO - distinguish between entries which have a way to buy _the same ROM_, and entries which have a way to buy _an enhanced ROM_ (say, a full version of a game's demo).

@asiekierka , right! I'd say those are anyway `commercial` but we can mark free/demo versions of the game with some kind of values like `free-demo` or `free-version` applied on the File object related to the ROM
