### ISSUE TITLE
Want to update a ROM

### ISSUE THREAD

**Issue by maxoakland** [gbdev/database#243]
My game Wink & the Broken Robot is on here, which I'm happy about. But the ROM is an older version. I'd like to update it to the latest version

How do I do that?

**Comment by avivace** [comment]
> My game Wink & the Broken Robot is on here, which I'm happy about. But the ROM is an older version. I'd like to update it to the latest version
> 
> How do I do that?

Can you fork the repo, clone your fork, update the the ROM and send a Pull Request? Otherwise it's fine to upload here as a comment the updated ROM, I can change it for you
