### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by Villagerjj** [gbdev/database#53]
i have been trying to add my files but it keeps denying me.
i don't understand how to upload my game to the GitHub
i have been trying to upload this file: https://github.com/Villagerjj/Linum/tree/master

**Comment by NieDzejkob** [comment]
Could you specify what you mean, exactly, by "it keeps denying me"? An error message or screenshot would be helpful.

You need to use the "add file" button in this repository (in the `entries` directory). GitHub will create a "fork" for you, which is your own copy of the repository, and then offer to create a "pull request", which will ask us to approve these changes.

**Comment by Villagerjj** [comment]
the add button states this: "Uploads are disabled.
File uploads require push access to this repository." also how do I make a pull request. the github help page is confusing

**Comment by IamRifki** [comment]
@Villagerjj Make a fork of this repository, add your file in the fork, then make a pull request. Uploads aren't enabled in the main repo to avoid people uploading nonsense to it.

**Comment by avivace** [comment]
Hi @Villagerjj , thank you for showing an interest in this project! We'd love to have your game.

Please, avoid writing in all caps in your titles/requests. It is equal to *shouting*, on the internet.
Thanks @NieDzejkob and @IamRifki for providing help on this! I just want to add this [link](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), it'll explain how to create a PR.

You can also take a look at the [PR](https://github.com/gbdev/database/pulls?q=is%3Apr+is%3Aclosed) we already merged here and see what files they add/how.

If anything else comes up, feel free to ask here!

**Comment by Villagerjj** [comment]
> Hi @Villagerjj , thank you for showing an interest in this project! We'd love to have your game.
> 
> Please, avoid writing in all caps in your titles/requests. It is equal to _shouting_, on the internet.
> Thanks @NieDzejkob and @IamRifki for providing help on this! I just want to add this [link](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), it'll explain how to create a PR.
> 
> You can also take a look at the [PR](https://github.com/gbdev/database/pulls?q=is%3Apr+is%3Aclosed) we already merged here and see what files they add/how.
> 
> If anything else comes up, feel free to ask here!

thanks for the help, sorry about the "shouting" i just was a little frustrated

**Comment by avivace** [comment]
You're welcome. Thank you for working through it. I merged #54
