### ISSUE TITLE
Entries problems

### ISSUE THREAD

**Issue by dag7dev** [gbdev/database#86]
```
├── Garpsters-Archaic-Rooms-of-Paranoia
│   ├── 20110402_garpsters_archaic_rooms_of_paranoia.png
│   ├── game.json
│   └── Garpsters_Archaic_Rooms_of_Paranoia__(Gameboy).png
[WARN]: no gb file

├── Snake-by-Yvar-de-Goffau
│   ├── 20180121_snake_(15-01-2018)_(gb_game).png
│   ├── game.json
│   └── Snake_Yvar_de_Goffau_(15-01-2018)_(Gameboy)
[WARN]: no gb file

```

**Comment by dag7dev** [comment]
Now, just those folders have some problems.
My suggestion is to push in my branch and remove/update those entries.

**Comment by dag7dev** [comment]
Yaronet thread:
```
#gb,furrtekk,Super Connard,sc_prod.gb,http://furrtek.free.fr/superconnard/sc_prod.gb,
# REASON: no screenshot available

#gb,refresh games,Waifu Clicker,waifuclicker.zip,https://ggj.s3.amazonaws.com/games/2016/01/31/1447/waifuclicker.zip,https://globalgamejam.org/sites/default/files/styles/game_sidebar__wide/public/game/featured_image/featured_image_33.png?itok=5ENHsFGI&timestamp=1454250586
# REASON: nested folder. This parser doesn't work with nested folder.

#gb,Jared Chansen,Up on the housetop,Up on the Housetop.gb,Up on the Housetop.gb,None
# REASON: no screenshot available

#gbc,Jaws-V Soft,Fatal Flame,Fatal_Flame_v2_(Gameboy).zip,https://pdroms.de/?__df=23041104093a23090408003a13573a4d22040800070a1c4c4b1f0c151b191b56565c531b191b50525c5552,https://pdroms.de/wp-content/uploads/2017/01/fatalflame_v2.png
# REASON: pdroms always gave problems
```

**Comment by avivace** [comment]
> Yaronet thread:
> 
> ```
> #gb,furrtekk,Super Connard,sc_prod.gb,http://furrtek.free.fr/superconnard/sc_prod.gb,
> # REASON: no screenshot available
> 
> #gb,refresh games,Waifu Clicker,waifuclicker.zip,https://ggj.s3.amazonaws.com/games/2016/01/31/1447/waifuclicker.zip,https://globalgamejam.org/sites/default/files/styles/game_sidebar__wide/public/game/featured_image/featured_image_33.png?itok=5ENHsFGI&timestamp=1454250586
> # REASON: nested folder. This parser doesn't work with nested folder.
> 
> #gb,Jared Chansen,Up on the housetop,Up on the Housetop.gb,Up on the Housetop.gb,None
> # REASON: no screenshot available
> 
> #gbc,Jaws-V Soft,Fatal Flame,Fatal_Flame_v2_(Gameboy).zip,https://pdroms.de/?__df=23041104093a23090408003a13573a4d22040800070a1c4c4b1f0c151b191b56565c531b191b50525c5552,https://pdroms.de/wp-content/uploads/2017/01/fatalflame_v2.png
> # REASON: pdroms always gave problems
> ```

You don't need to provide a screenshot.. there are entries without one already
