### ISSUE TITLE
Hackrom support

### ISSUE THREAD

**Issue by avivace** [gbdev/database#96]
Add special schema case for Hackrom (IPS patches + checksums of supported ROMs)

Consider also UPS/APS/BPS/RUP/PPF/xdelta

**Comment by dag7dev** [comment]
could be interesting something like
```
{
...
"patches": [
    {
        "name": ...,
        "path": "patch/patch.bps",
        "checksum": "...",
        "type": <translation / hackrom (vanilla QOL) / hackrom (full)>
    },
    ...
]
}
```

OR we can just leave the opportunity to user to upload its own patch (see https://github.com/marcrobledo/RomPatcher.js/ as base)
